server:
  port: 7070

spring:
  datasource:
    url: jdbc:mysql://60.205.181.203:3306/integral?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapperLocations: classpath:mapper/*.xml
logging:
  config: classpath:config/logback.xml

