server:
  port: 7070

spring:
  datasource:
    url: jdbc:mysql://1.14.108.113:3306/work_order?characterEncoding=utf-8&amp&serverTimezone=UTC&amp&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin

mybatis:
  mapperLocations: classpath:mapper/*.xml

logging:
  config: classpath:config/logback.xml

