server:
  port: 7070

spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/chemical?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://127.0.0.1:3306/edu-auth?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
#    password: XUE_ke_274
#    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  mapperLocations: classpath:mapper/*.xml

logging:
  config: classpath:config/logback.xml

